run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - revive
    - gofmt
  disable:
    - errcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019.*grpc.DialContext is deprecated"

linters-settings:
  revive:
    severity: warning
