run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - revive
    - gofmt

issues:
  exclude-use-default: false

linters-settings:
  revive:
    severity: warning
